/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * REMOVE.java
 *
 * Created on Oct 23, 2013, 10:16:54 AM
 */

package HOSPITAL_MANAGEMENT;

import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author RMSA
 */
public class REMOVE extends javax.swing.JFrame {

    /** Creates new form REMOVE */
    public REMOVE() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tf1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 1000));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24));
        jLabel1.setForeground(new java.awt.Color(0, 255, 0));
        jLabel1.setText("HAD YOUR HART CARE WITH US");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(150, 20, 380, 40);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 18));
        jLabel2.setText("Patient no.");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 190, 90, 30);
        getContentPane().add(tf1);
        tf1.setBounds(250, 190, 200, 30);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 24));
        jLabel3.setForeground(new java.awt.Color(0, 255, 0));
        jLabel3.setText("WISH YOU A HAPPY LIFE");
        jLabel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(180, 60, 300, 40);

        jButton1.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18));
        jButton1.setText("REMOVE");
        jButton1.setToolTipText("remove your ward");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(70, 310, 111, 90);

        jButton2.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18));
        jButton2.setText("HOME");
        jButton2.setToolTipText("move main panel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(270, 310, 100, 100);

        jButton3.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18));
        jButton3.setText("EXIT");
        jButton3.setToolTipText("end application");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(470, 320, 100, 90);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HOSPITAL_MANAGEMENT/Medical_Large.gif"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 910, 680);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        System.exit(0);

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new MAIN().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       try{
        Class.forName("java.sql.DriverManager");
        Connection con= (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/gaurav","root","12345");
        String a;
        a=tf1.getText();
        String e="delete from kumar where patient_no="+a+";";
        Statement st=con.createStatement();
        st.executeUpdate(e);
        JOptionPane.showMessageDialog(null,"RECORD IS REMOVED");
        tf1.setText("");
        }
        catch(Exception e)
        {
        JOptionPane.showMessageDialog(null,e.getMessage());
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new REMOVE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField tf1;
    // End of variables declaration//GEN-END:variables

}
