/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ALL;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class COUNT extends javax.swing.JFrame {

    /**
     * Creates new form COUNT
     */
    public COUNT() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jc1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jt1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 1000));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 51));
        jLabel1.setText("STATISTICS");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(350, 40, 230, 40);

        jc1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT DEPARTMENT-:", "COMPUTER SCIENCE(CSE)", "MECHANICAL(MECH)", "CIVIL(CIVIL)", "AERONAUTICAL(AERO)", "ELECTRICAL(EE)", "ELECTRONICS& ELECTRONICS(EEE)" }));
        getContentPane().add(jc1);
        jc1.setBounds(670, 110, 170, 30);

        jButton1.setText("SHOW");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(910, 130, 90, 70);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(630, 200, 230, 170);

        jt1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NAME", "D.O.B"
            }
        ));
        jScrollPane2.setViewportView(jt1);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(60, 110, 530, 430);

        jButton2.setText("HOME");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(660, 420, 80, 70);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel jl=(DefaultTableModel)jt1.getModel();
        int row=jl.getRowCount();
        for(int i=0;i<row;i++){
            jl.removeRow(i);
        }
        start:{
        try{
            String depnew = new String();
            String dep=((String)jc1.getSelectedItem()).toUpperCase();
            
            if(dep.equals("SELECT DEPARTMENT-:")){
                JOptionPane.showMessageDialog(this,"PLEASE GIVE RIGHT DEPARTMENT");
            break start;
            }
            char[] dept=new char[5];
            dept=dep.toCharArray();
            for(int r=0;r<dept.length;r++){
                if(dept[r]=='('){
                    while(dept[r]!=')'){
                        r++;
                        char a=dept[r];
                        depnew+=a;
                    }
                }
            }            
         Class.forName("java.sql.DriverManager");
        Connection con=(Connection)DriverManager.getConnection
        ("jdbc:mysql://localhost:3306/project","root","12345");
        String sql="select(id,name,dob) from teacher_data where dept=?";
        PreparedStatement stmt=con.prepareStatement(sql);
        stmt.setString(1,depnew);
        ResultSet rs=stmt.executeQuery();
        while(rs.next()){
            String id=rs.getString("id");
        String name=rs.getString("name");
        String dob=rs.getString("dob");
        jl.addRow(new Object[]{id,name,dob});
        }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this,e);
        }
        }      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new HOME().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(COUNT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(COUNT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(COUNT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(COUNT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new COUNT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JComboBox<String> jc1;
    private javax.swing.JTable jt1;
    // End of variables declaration//GEN-END:variables
}
