package ALL;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.Statement;
import javax.swing.*;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author HP
 */
public class DATA_ENTRY extends javax.swing.JFrame {

    
    /**
     * Creates new form frame2
     */
    public DATA_ENTRY() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tf1 = new javax.swing.JTextField();
        tf2 = new javax.swing.JTextField();
        dt1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        tf4 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tf5 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        dt2 = new javax.swing.JTextField();
        dt3 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tf7 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setMinimumSize(new java.awt.Dimension(1000, 1000));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 51));
        jLabel1.setText("       DATA ENTRY");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(290, 40, 450, 50);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("NAME");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 200, 160, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("I_D NO");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 260, 70, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("DATE_BIRTH");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 320, 150, 30);

        tf1.setToolTipText("ENTER NAME");
        tf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf1ActionPerformed(evt);
            }
        });
        getContentPane().add(tf1);
        tf1.setBounds(250, 190, 210, 30);

        tf2.setToolTipText("ENTER I_D NO");
        getContentPane().add(tf2);
        tf2.setBounds(250, 250, 210, 30);

        dt1.setToolTipText("DATE_OF_BIRTH");
        dt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dt1ActionPerformed(evt);
            }
        });
        getContentPane().add(dt1);
        dt1.setBounds(250, 320, 60, 30);

        jButton1.setText("PROCEED");
        jButton1.setToolTipText("PROCEED FURTHER");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(730, 170, 100, 80);

        jButton2.setText("CLEAR");
        jButton2.setToolTipText("CLEAR ALL FIELDS");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(730, 290, 100, 80);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("DEPT");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(50, 410, 120, 30);
        getContentPane().add(tf4);
        tf4.setBounds(250, 410, 210, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("QUALIFICATION");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(40, 480, 150, 30);
        getContentPane().add(tf5);
        tf5.setBounds(250, 480, 210, 30);

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("USE / SEPARATOR");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(480, 490, 120, 20);
        getContentPane().add(dt2);
        dt2.setBounds(340, 320, 70, 30);
        getContentPane().add(dt3);
        dt3.setBounds(460, 320, 80, 30);

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("DAY");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(250, 360, 60, 20);

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("MONTH");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(350, 360, 36, 14);

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("YEAR");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(480, 360, 40, 14);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("DESIGNATION");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 550, 180, 30);
        getContentPane().add(tf7);
        tf7.setBounds(250, 550, 210, 30);

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Downloads\\teacher\\what_is_creative_teaching-e1433788418645.jpeg")); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(40, 50, 910, 580);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf1ActionPerformed

    private void dt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dt1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        tf1.setText("");
        tf2.setText("");
        dt1.setText("");
         dt2.setText("");
          dt3.setText("");
           tf4.setText("");
             tf5.setText("");
              tf7.setText("");
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
//Calendar can=Calendar.getInstance();
canbreak:{
try{
Class.forName("java.sql.DriverManager");
Connection con=(Connection)DriverManager.getConnection
        ("jdbc:mysql://localhost:3306/project","root","12345");
String name=tf1.getText().toUpperCase();
String id=tf2.getText().toUpperCase();
String day=dt1.getText().toUpperCase();
String month=dt2.getText().toUpperCase();
String year=dt3.getText().toUpperCase();
String date=day+"-"+month+"-"+year;
String dep=tf4.getText().toUpperCase();
String quali=tf5.getText().toUpperCase();
String degi=tf7.getText().toUpperCase();
String max="set global max_allowed_packet=104857600;";
String sql="insert into teacher_data(id,name,dept,dob,qualification,desig)values(?,?,?,?,?,?);";
PreparedStatement stmt=con.prepareStatement(sql);
Statement st=con.createStatement();
stmt.setString(1,id);
stmt.setString(2,name);
stmt.setString(3,dep);
stmt.setString(4,date);
stmt.setString(5,quali);
stmt.setString(6,degi);
st.executeQuery(max);   //SETPACKET QUERY
String sql1="create table ?(subject varchar(25) default 'FREE',room_no varchar(4) default '0000',year varchar(15) default 'NO ENTRY',timing varchar(15) default 'NO ENTRY',days varchar(11) default 'NO ENTRY');";
PreparedStatement stmt1=con.prepareStatement(sql1);
stmt1.setString(1,id);
int ok=stmt.executeUpdate();
int ok1=stmt1.executeUpdate();
System.out.print(ok1);
if(ok>=0){
    JOptionPane.showMessageDialog(this,("data entered correctly").toUpperCase());
    if(ok1<0)
        JOptionPane.showMessageDialog(this,("problem with table creation").toUpperCase());
    else{
    this.dispose();
   new pic().setVisible(true);}
}
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this,e);
        }}
    
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DATA_ENTRY.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DATA_ENTRY.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DATA_ENTRY.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DATA_ENTRY.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DATA_ENTRY().setVisible(true);
            }
        });
           
     
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField dt1;
    private javax.swing.JTextField dt2;
    private javax.swing.JTextField dt3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JTextField tf1;
    private javax.swing.JTextField tf2;
    private javax.swing.JTextField tf4;
    private javax.swing.JTextField tf5;
    private javax.swing.JTextField tf7;
    // End of variables declaration//GEN-END:variables
}
