/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ALL;

import java.awt.HeadlessException;
import java.awt.Image;
import java.sql.Blob;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class REFERENCE extends javax.swing.JFrame {

    /**
     * Creates new form REFERENC
     */
    public REFERENCE() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tf1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jl1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jt1 = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta1 = new javax.swing.JTextArea();
        jc2 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setBackground(new java.awt.Color(255, 240, 106));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setMinimumSize(new java.awt.Dimension(1300, 1000));
        setResizable(false);
        getContentPane().setLayout(null);

        tf1.setToolTipText("GIVE INPUT");
        tf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf1ActionPerformed(evt);
            }
        });
        getContentPane().add(tf1);
        tf1.setBounds(180, 120, 200, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel2.setText("TEACHER I_D");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 120, 120, 40);

        jButton1.setText("OK");
        jButton1.setToolTipText("CLICK TO PROCEED\n");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(540, 100, 100, 90);

        jButton2.setText("REFRESH");
        jButton2.setToolTipText("CLEAR CHOICES");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(410, 120, 90, 40);

        jl1.setToolTipText("PHOTO");
        jl1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 255, 255)));
        getContentPane().add(jl1);
        jl1.setBounds(760, 30, 410, 290);

        jt1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SUBJECT", "ROOM_NO", "TIME", "YEAR"
            }
        ));
        jt1.setAlignmentX(1.0F);
        jt1.setAlignmentY(1.0F);
        jt1.setIntercellSpacing(new java.awt.Dimension(1, 5));
        jt1.setRowHeight(30);
        jScrollPane2.setViewportView(jt1);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(10, 330, 730, 330);

        ta1.setEditable(false);
        ta1.setColumns(20);
        ta1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        ta1.setRows(5);
        jScrollPane1.setViewportView(ta1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(760, 330, 410, 330);

        jc2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ENTER DAY_NAME", "MONDAY", "TUESDAY", "WEDNESDAY", "THRUSDAY", "FRIDAY", "SATURDAY" }));
        jc2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jc2FocusGained(evt);
            }
        });
        jc2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jc2ActionPerformed(evt);
            }
        });
        getContentPane().add(jc2);
        jc2.setBounds(60, 220, 250, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 51));
        jLabel1.setText("REFERENCE");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(250, 30, 400, 50);

        jButton4.setText("TEACHER LIST");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(380, 220, 120, 30);

        jButton3.setText("EXIT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(540, 210, 100, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tm=(DefaultTableModel)jt1.getModel();
        start:{
            try{
                Class.forName("java.sql.DriverManager");
                Connection con =(Connection)DriverManager.getConnection
        ("jdbc:mysql://localhost:3306/project","root","12345");
                String input=tf1.getText().toUpperCase();
                String day=((String)jc2.getSelectedItem()).toUpperCase();
                if(day.equals("ENTER DAY_NAME")){
                    JOptionPane.showMessageDialog(this,"Please Enter Valid Day");
                    this.dispose();
                    new REFERENCE().setVisible(true);
                    break start;
                }               
                   String start="use project;";
              PreparedStatement st=con.prepareStatement(start);
              int go=st.executeUpdate(start);
          if(go<0){
          JOptionPane.showMessageDialog(this,"Problem in connection");
      }
                String sql="select *from ? where day=?;";
             PreparedStatement sta=con.prepareStatement(sql);
             sta.setString(1,input);
             sta.setString(2,day);
                 ResultSet rs=sta.executeQuery(sql);
               while(rs.next()){
                    String subject=rs.getString("subject");
                    int room=rs.getInt("room_no");
                    String time=rs.getString("timing");
                    String year=rs.getString("year");
                    tm.addRow(new Object[]{subject.toUpperCase(),room,time.toUpperCase(),year.toUpperCase()});
                }
                String sql1="select *from teacher_data where id=?;";
                PreparedStatement st1=con.prepareStatement(sql1);
                st1.setString(1,input);
                ResultSet rs1=st.executeQuery(sql1);
                while(rs1.next()){
                    String name=rs1.getString("name");
                    String dept=rs1.getString("dept");
                    String dob=rs1.getString("dob");
                    String quali=rs1.getString("qualification");
                    ta1.setText("NAME="+(name.toUpperCase())+"\nDEPARTMENT="+dept.toUpperCase()+"\nDATE OF BIRTH="+dob+"\nQUALIFICATION="+quali.toUpperCase());
                    Blob blob = rs1.getBlob("image");
                   byte[] content = blob.getBytes(1L,(int)blob.length());//L for length
         ImageIcon ik = new ImageIcon(content);
         Image img = ik.getImage();
         Image newimg = img.getScaledInstance(410,290, java.awt.Image.SCALE_SMOOTH);
         ik = new ImageIcon(newimg);
        jl1.setIcon(ik);
                 /* //  ImageIcon image = new ImageIcon((Image) blob);
                   //jl1.setIcon(image);
                    byte[] image1 = (byte[])blob.getBytes(6,ALLBITS);
                    ImageIcon image = new ImageIcon();
                    jl1.setIcon((Icon) image);
                    getContentPane().add(jl1);
                    setVisible(true);
 
                    // jl1.setIcon((Icon) blob);*/

                }}
                catch(ClassNotFoundException | SQLException | HeadlessException e){
                    JOptionPane.showMessageDialog(this,e);
                }}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new REFERENCE().setVisible(true);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jc2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jc2ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jc2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        new list().setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        end:{
        try{  
           String s=JOptionPane.showInputDialog("Enter password:");
        if(s.equals("12345")){
            this.dispose();}
        if(s == null){
            break end;
        }
             
       }
       catch(Exception e){
           JOptionPane.showMessageDialog(this, e);
       }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jc2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jc2FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jc2FocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(REFERENCE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(REFERENCE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(REFERENCE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(REFERENCE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new REFERENCE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> jc2;
    private javax.swing.JLabel jl1;
    private javax.swing.JTable jt1;
    private javax.swing.JTextArea ta1;
    private javax.swing.JTextField tf1;
    // End of variables declaration//GEN-END:variables
}
